spring:
  profiles:
    active: local
management:
  endpoints:
    web:
      exposure: # /actuator/health
        include: health, info  # health와 info 엔드포인트만 노출
  endpoint:
    health:
      show-details: never     # 상세 정보 숨김 (보안 목적)


